---
server:
  port: 8099
  
eureka:
  server:
    enable-self-preservation: false 
    waitTimeInMsWhenSyncEmpty: 0   
  client:
    registerWithEureka: false
    fetchRegistry: false
                 