---
spring:
  cloud:
    config:
      server:
        git:
         uri: https://github.com/zhafi/building-microservices-spring-cloud
         search-paths: config-server-properties
                                          
server:
  port: 8001          